---

notifications:
  irc:
    channels:
      - "chat.freenode.net#kubevirt"
    on_success: change
    on_failure: always

addons:
  apt:
    packages:
      - aspell
      - aspell-en

before_script:
- gem install ascii_binder

script:
  - make docs

deploy:
  provider: script
  script: bash push.sh
  on:
    branch: master
